<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>groupId</groupId>
    <artifactId>JarScans</artifactId>
    <version>1.0-SNAPSHOT</version>
    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>  
         
	<!-- Source: https://mvnrepository.com/artifact/commons-beanutils/commons-beanutils -->
	<dependency>
		<groupId>commons-beanutils</groupId>
		<artifactId>commons-beanutils</artifactId>
		<version>1.11.0</version>
		<scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/commons-codec/commons-codec -->
	<dependency>
		<groupId>commons-codec</groupId>
		<artifactId>commons-codec</artifactId>
		<version>1.21.0</version>
		<scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-collections4 -->
	<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-collections4</artifactId>
		<version>4.5.0</version>
		<scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-compress -->
	<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-compress</artifactId>
		<version>1.27.1</version>
		<scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/commons-digester/commons-digester -->
	<dependency>
		<groupId>commons-digester</groupId>
		<artifactId>commons-digester</artifactId>
		<version>2.1</version>
		<scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-fileupload2-core -->
	<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-fileupload2-core</artifactId>
		<version>2.0.0-M4</version>
		<scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-fileupload2-jakarta-servlet6 -->
	<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-fileupload2-jakarta-servlet6</artifactId>
		<version>2.0.0-M4</version>
		<scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/commons-io/commons-io -->
	<dependency>
		<groupId>commons-io</groupId>
		<artifactId>commons-io</artifactId>
		<version>2.21.0</version>
		<scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-lang3 -->
	<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-lang3</artifactId>
		<version>3.20.0</version>
		<scope>compile</scope>
	</dependency>


	<!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-text -->
	<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-text</artifactId>
		<version>1.15.0</version>
		<scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-math3 -->
	<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-math3</artifactId>
		<version>3.6.1</version>
		<scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/org.apache.commons/commons-text -->
	<dependency>
		<groupId>org.apache.commons</groupId>
		<artifactId>commons-text</artifactId>
		<version>1.13.0</version>
		<scope>compile</scope>
	</dependency>

	<!-- Source: https://mvnrepository.com/artifact/commons-validator/commons-validator -->
	<dependency>
		<groupId>commons-validator</groupId>
		<artifactId>commons-validator</artifactId>
		<version>1.9.0</version>
		<scope>compile</scope>
	</dependency>

    </dependencies>
</project>
